services:
  # Base de datos (Persistencia de datos solicitada) [cite: 7]
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: catalog
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # Tu servidor Node.js [cite: 5]
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:password123@db:5432/catalog
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend